// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: api/proto/tsundoku/book/v1/book.proto

package bookv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Book Status Enum
type BookStatus int32

const (
	BookStatus_BOOK_STATUS_UNSPECIFIED BookStatus = 0
	BookStatus_BOOK_STATUS_UNREAD      BookStatus = 1
	BookStatus_BOOK_STATUS_READING     BookStatus = 2
	BookStatus_BOOK_STATUS_FINISHED    BookStatus = 3
)

// Enum value maps for BookStatus.
var (
	BookStatus_name = map[int32]string{
		0: "BOOK_STATUS_UNSPECIFIED",
		1: "BOOK_STATUS_UNREAD",
		2: "BOOK_STATUS_READING",
		3: "BOOK_STATUS_FINISHED",
	}
	BookStatus_value = map[string]int32{
		"BOOK_STATUS_UNSPECIFIED": 0,
		"BOOK_STATUS_UNREAD":      1,
		"BOOK_STATUS_READING":     2,
		"BOOK_STATUS_FINISHED":    3,
	}
)

func (x BookStatus) Enum() *BookStatus {
	p := new(BookStatus)
	*p = x
	return p
}

func (x BookStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_tsundoku_book_v1_book_proto_enumTypes[0].Descriptor()
}

func (BookStatus) Type() protoreflect.EnumType {
	return &file_api_proto_tsundoku_book_v1_book_proto_enumTypes[0]
}

func (x BookStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookStatus.Descriptor instead.
func (BookStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{0}
}

// Book Message
type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Isbn          string                 `protobuf:"bytes,5,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Status        BookStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=tsundoku.book.v1.BookStatus" json:"status,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *Book) GetStatus() BookStatus {
	if x != nil {
		return x.Status
	}
	return BookStatus_BOOK_STATUS_UNSPECIFIED
}

func (x *Book) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Book) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Book) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request Messages
type CreateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Isbn          string                 `protobuf:"bytes,3,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Status        BookStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=tsundoku.book.v1.BookStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBookRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *CreateBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *CreateBookRequest) GetStatus() BookStatus {
	if x != nil {
		return x.Status
	}
	return BookStatus_BOOK_STATUS_UNSPECIFIED
}

type GetBooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *BookStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=tsundoku.book.v1.BookStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksRequest) Reset() {
	*x = GetBooksRequest{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksRequest) ProtoMessage() {}

func (x *GetBooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksRequest.ProtoReflect.Descriptor instead.
func (*GetBooksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{2}
}

func (x *GetBooksRequest) GetStatus() BookStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return BookStatus_BOOK_STATUS_UNSPECIFIED
}

type GetBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookRequest) Reset() {
	*x = GetBookRequest{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookRequest) ProtoMessage() {}

func (x *GetBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookRequest.ProtoReflect.Descriptor instead.
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{3}
}

func (x *GetBookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Isbn          string                 `protobuf:"bytes,4,opt,name=isbn,proto3" json:"isbn,omitempty"`
	Status        BookStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=tsundoku.book.v1.BookStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateBookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBookRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBookRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *UpdateBookRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *UpdateBookRequest) GetStatus() BookStatus {
	if x != nil {
		return x.Status
	}
	return BookStatus_BOOK_STATUS_UNSPECIFIED
}

type UpdateBookStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        BookStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=tsundoku.book.v1.BookStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookStatusRequest) Reset() {
	*x = UpdateBookStatusRequest{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookStatusRequest) ProtoMessage() {}

func (x *UpdateBookStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBookStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBookStatusRequest) GetStatus() BookStatus {
	if x != nil {
		return x.Status
	}
	return BookStatus_BOOK_STATUS_UNSPECIFIED
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UploadBookImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookId        string                 `protobuf:"bytes,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBookImageRequest) Reset() {
	*x = UploadBookImageRequest{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBookImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBookImageRequest) ProtoMessage() {}

func (x *UploadBookImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBookImageRequest.ProtoReflect.Descriptor instead.
func (*UploadBookImageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{7}
}

func (x *UploadBookImageRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

func (x *UploadBookImageRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *UploadBookImageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadBookImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

// Response Messages
type GetBooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksResponse) Reset() {
	*x = GetBooksResponse{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksResponse) ProtoMessage() {}

func (x *GetBooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksResponse.ProtoReflect.Descriptor instead.
func (*GetBooksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{8}
}

func (x *GetBooksResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

type DeleteBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadBookImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Book                  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadBookImageResponse) Reset() {
	*x = UploadBookImageResponse{}
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadBookImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadBookImageResponse) ProtoMessage() {}

func (x *UploadBookImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_book_v1_book_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadBookImageResponse.ProtoReflect.Descriptor instead.
func (*UploadBookImageResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP(), []int{10}
}

func (x *UploadBookImageResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

var File_api_proto_tsundoku_book_v1_book_proto protoreflect.FileDescriptor

const file_api_proto_tsundoku_book_v1_book_proto_rawDesc = "" +
	"\n" +
	"%api/proto/tsundoku/book/v1/book.proto\x12\x10tsundoku.book.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x02\n" +
	"\x04Book\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x12\n" +
	"\x04isbn\x18\x05 \x01(\tR\x04isbn\x124\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1c.tsundoku.book.v1.BookStatusR\x06status\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8b\x01\n" +
	"\x11CreateBookRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x12\n" +
	"\x04isbn\x18\x03 \x01(\tR\x04isbn\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.tsundoku.book.v1.BookStatusR\x06status\"W\n" +
	"\x0fGetBooksRequest\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.tsundoku.book.v1.BookStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\" \n" +
	"\x0eGetBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9b\x01\n" +
	"\x11UpdateBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x12\n" +
	"\x04isbn\x18\x04 \x01(\tR\x04isbn\x124\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1c.tsundoku.book.v1.BookStatusR\x06status\"_\n" +
	"\x17UpdateBookStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.tsundoku.book.v1.BookStatusR\x06status\"#\n" +
	"\x11DeleteBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8f\x01\n" +
	"\x16UploadBookImageRequest\x12\x17\n" +
	"\abook_id\x18\x01 \x01(\tR\x06bookId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\"@\n" +
	"\x10GetBooksResponse\x12,\n" +
	"\x05books\x18\x01 \x03(\v2\x16.tsundoku.book.v1.BookR\x05books\".\n" +
	"\x12DeleteBookResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\x17UploadBookImageResponse\x12*\n" +
	"\x04book\x18\x01 \x01(\v2\x16.tsundoku.book.v1.BookR\x04book*t\n" +
	"\n" +
	"BookStatus\x12\x1b\n" +
	"\x17BOOK_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BOOK_STATUS_UNREAD\x10\x01\x12\x17\n" +
	"\x13BOOK_STATUS_READING\x10\x02\x12\x18\n" +
	"\x14BOOK_STATUS_FINISHED\x10\x032\xac\x06\n" +
	"\vBookService\x12c\n" +
	"\n" +
	"CreateBook\x12#.tsundoku.book.v1.CreateBookRequest\x1a\x16.tsundoku.book.v1.Book\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/books\x12h\n" +
	"\bGetBooks\x12!.tsundoku.book.v1.GetBooksRequest\x1a\".tsundoku.book.v1.GetBooksResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/books\x12_\n" +
	"\aGetBook\x12 .tsundoku.book.v1.GetBookRequest\x1a\x16.tsundoku.book.v1.Book\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/books/{id}\x12h\n" +
	"\n" +
	"UpdateBook\x12#.tsundoku.book.v1.UpdateBookRequest\x1a\x16.tsundoku.book.v1.Book\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/api/v1/books/{id}\x12{\n" +
	"\x10UpdateBookStatus\x12).tsundoku.book.v1.UpdateBookStatusRequest\x1a\x16.tsundoku.book.v1.Book\"$\x82\xd3\xe4\x93\x02\x1e:\x01*2\x19/api/v1/books/{id}/status\x12s\n" +
	"\n" +
	"DeleteBook\x12#.tsundoku.book.v1.DeleteBookRequest\x1a$.tsundoku.book.v1.DeleteBookResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/api/v1/books/{id}\x12\x90\x01\n" +
	"\x0fUploadBookImage\x12(.tsundoku.book.v1.UploadBookImageRequest\x1a).tsundoku.book.v1.UploadBookImageResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/books/{book_id}/imageB5Z3meta-tsundr-backend/api/proto/tsundoku/book/v1;bookv1b\x06proto3"

var (
	file_api_proto_tsundoku_book_v1_book_proto_rawDescOnce sync.Once
	file_api_proto_tsundoku_book_v1_book_proto_rawDescData []byte
)

func file_api_proto_tsundoku_book_v1_book_proto_rawDescGZIP() []byte {
	file_api_proto_tsundoku_book_v1_book_proto_rawDescOnce.Do(func() {
		file_api_proto_tsundoku_book_v1_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_tsundoku_book_v1_book_proto_rawDesc), len(file_api_proto_tsundoku_book_v1_book_proto_rawDesc)))
	})
	return file_api_proto_tsundoku_book_v1_book_proto_rawDescData
}

var file_api_proto_tsundoku_book_v1_book_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_tsundoku_book_v1_book_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_tsundoku_book_v1_book_proto_goTypes = []any{
	(BookStatus)(0),                 // 0: tsundoku.book.v1.BookStatus
	(*Book)(nil),                    // 1: tsundoku.book.v1.Book
	(*CreateBookRequest)(nil),       // 2: tsundoku.book.v1.CreateBookRequest
	(*GetBooksRequest)(nil),         // 3: tsundoku.book.v1.GetBooksRequest
	(*GetBookRequest)(nil),          // 4: tsundoku.book.v1.GetBookRequest
	(*UpdateBookRequest)(nil),       // 5: tsundoku.book.v1.UpdateBookRequest
	(*UpdateBookStatusRequest)(nil), // 6: tsundoku.book.v1.UpdateBookStatusRequest
	(*DeleteBookRequest)(nil),       // 7: tsundoku.book.v1.DeleteBookRequest
	(*UploadBookImageRequest)(nil),  // 8: tsundoku.book.v1.UploadBookImageRequest
	(*GetBooksResponse)(nil),        // 9: tsundoku.book.v1.GetBooksResponse
	(*DeleteBookResponse)(nil),      // 10: tsundoku.book.v1.DeleteBookResponse
	(*UploadBookImageResponse)(nil), // 11: tsundoku.book.v1.UploadBookImageResponse
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_api_proto_tsundoku_book_v1_book_proto_depIdxs = []int32{
	0,  // 0: tsundoku.book.v1.Book.status:type_name -> tsundoku.book.v1.BookStatus
	12, // 1: tsundoku.book.v1.Book.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: tsundoku.book.v1.Book.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: tsundoku.book.v1.CreateBookRequest.status:type_name -> tsundoku.book.v1.BookStatus
	0,  // 4: tsundoku.book.v1.GetBooksRequest.status:type_name -> tsundoku.book.v1.BookStatus
	0,  // 5: tsundoku.book.v1.UpdateBookRequest.status:type_name -> tsundoku.book.v1.BookStatus
	0,  // 6: tsundoku.book.v1.UpdateBookStatusRequest.status:type_name -> tsundoku.book.v1.BookStatus
	1,  // 7: tsundoku.book.v1.GetBooksResponse.books:type_name -> tsundoku.book.v1.Book
	1,  // 8: tsundoku.book.v1.UploadBookImageResponse.book:type_name -> tsundoku.book.v1.Book
	2,  // 9: tsundoku.book.v1.BookService.CreateBook:input_type -> tsundoku.book.v1.CreateBookRequest
	3,  // 10: tsundoku.book.v1.BookService.GetBooks:input_type -> tsundoku.book.v1.GetBooksRequest
	4,  // 11: tsundoku.book.v1.BookService.GetBook:input_type -> tsundoku.book.v1.GetBookRequest
	5,  // 12: tsundoku.book.v1.BookService.UpdateBook:input_type -> tsundoku.book.v1.UpdateBookRequest
	6,  // 13: tsundoku.book.v1.BookService.UpdateBookStatus:input_type -> tsundoku.book.v1.UpdateBookStatusRequest
	7,  // 14: tsundoku.book.v1.BookService.DeleteBook:input_type -> tsundoku.book.v1.DeleteBookRequest
	8,  // 15: tsundoku.book.v1.BookService.UploadBookImage:input_type -> tsundoku.book.v1.UploadBookImageRequest
	1,  // 16: tsundoku.book.v1.BookService.CreateBook:output_type -> tsundoku.book.v1.Book
	9,  // 17: tsundoku.book.v1.BookService.GetBooks:output_type -> tsundoku.book.v1.GetBooksResponse
	1,  // 18: tsundoku.book.v1.BookService.GetBook:output_type -> tsundoku.book.v1.Book
	1,  // 19: tsundoku.book.v1.BookService.UpdateBook:output_type -> tsundoku.book.v1.Book
	1,  // 20: tsundoku.book.v1.BookService.UpdateBookStatus:output_type -> tsundoku.book.v1.Book
	10, // 21: tsundoku.book.v1.BookService.DeleteBook:output_type -> tsundoku.book.v1.DeleteBookResponse
	11, // 22: tsundoku.book.v1.BookService.UploadBookImage:output_type -> tsundoku.book.v1.UploadBookImageResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_tsundoku_book_v1_book_proto_init() }
func file_api_proto_tsundoku_book_v1_book_proto_init() {
	if File_api_proto_tsundoku_book_v1_book_proto != nil {
		return
	}
	file_api_proto_tsundoku_book_v1_book_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_tsundoku_book_v1_book_proto_rawDesc), len(file_api_proto_tsundoku_book_v1_book_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_tsundoku_book_v1_book_proto_goTypes,
		DependencyIndexes: file_api_proto_tsundoku_book_v1_book_proto_depIdxs,
		EnumInfos:         file_api_proto_tsundoku_book_v1_book_proto_enumTypes,
		MessageInfos:      file_api_proto_tsundoku_book_v1_book_proto_msgTypes,
	}.Build()
	File_api_proto_tsundoku_book_v1_book_proto = out.File
	file_api_proto_tsundoku_book_v1_book_proto_goTypes = nil
	file_api_proto_tsundoku_book_v1_book_proto_depIdxs = nil
}
