// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: api/proto/tsundoku/auth/v1/auth.proto

package authv1

import (
	v1 "meta-tsundr-backend/api/proto/tsundoku/user/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Authentication Response
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *v1.User               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_api_proto_tsundoku_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuthResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// Request Messages
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_tsundoku_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_proto_tsundoku_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_api_proto_tsundoku_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsundoku_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsundoku_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_api_proto_tsundoku_auth_v1_auth_proto protoreflect.FileDescriptor

const file_api_proto_tsundoku_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"%api/proto/tsundoku/auth/v1/auth.proto\x12\x10tsundoku.auth.v1\x1a\x1cgoogle/api/annotations.proto\x1a%api/proto/tsundoku/user/v1/user.proto\"o\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12*\n" +
	"\x04user\x18\x02 \x01(\v2\x16.tsundoku.user.v1.UserR\x04user\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"W\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x13RefreshTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xde\x02\n" +
	"\vAuthService\x12o\n" +
	"\bRegister\x12!.tsundoku.auth.v1.RegisterRequest\x1a\x1e.tsundoku.auth.v1.AuthResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/auth/register\x12f\n" +
	"\x05Login\x12\x1e.tsundoku.auth.v1.LoginRequest\x1a\x1e.tsundoku.auth.v1.AuthResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/auth/login\x12v\n" +
	"\fRefreshToken\x12%.tsundoku.auth.v1.RefreshTokenRequest\x1a\x1e.tsundoku.auth.v1.AuthResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/auth/refreshB5Z3meta-tsundr-backend/api/proto/tsundoku/auth/v1;authv1b\x06proto3"

var (
	file_api_proto_tsundoku_auth_v1_auth_proto_rawDescOnce sync.Once
	file_api_proto_tsundoku_auth_v1_auth_proto_rawDescData []byte
)

func file_api_proto_tsundoku_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_api_proto_tsundoku_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_api_proto_tsundoku_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_tsundoku_auth_v1_auth_proto_rawDesc), len(file_api_proto_tsundoku_auth_v1_auth_proto_rawDesc)))
	})
	return file_api_proto_tsundoku_auth_v1_auth_proto_rawDescData
}

var file_api_proto_tsundoku_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_tsundoku_auth_v1_auth_proto_goTypes = []any{
	(*AuthResponse)(nil),        // 0: tsundoku.auth.v1.AuthResponse
	(*RegisterRequest)(nil),     // 1: tsundoku.auth.v1.RegisterRequest
	(*LoginRequest)(nil),        // 2: tsundoku.auth.v1.LoginRequest
	(*RefreshTokenRequest)(nil), // 3: tsundoku.auth.v1.RefreshTokenRequest
	(*v1.User)(nil),             // 4: tsundoku.user.v1.User
}
var file_api_proto_tsundoku_auth_v1_auth_proto_depIdxs = []int32{
	4, // 0: tsundoku.auth.v1.AuthResponse.user:type_name -> tsundoku.user.v1.User
	1, // 1: tsundoku.auth.v1.AuthService.Register:input_type -> tsundoku.auth.v1.RegisterRequest
	2, // 2: tsundoku.auth.v1.AuthService.Login:input_type -> tsundoku.auth.v1.LoginRequest
	3, // 3: tsundoku.auth.v1.AuthService.RefreshToken:input_type -> tsundoku.auth.v1.RefreshTokenRequest
	0, // 4: tsundoku.auth.v1.AuthService.Register:output_type -> tsundoku.auth.v1.AuthResponse
	0, // 5: tsundoku.auth.v1.AuthService.Login:output_type -> tsundoku.auth.v1.AuthResponse
	0, // 6: tsundoku.auth.v1.AuthService.RefreshToken:output_type -> tsundoku.auth.v1.AuthResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_tsundoku_auth_v1_auth_proto_init() }
func file_api_proto_tsundoku_auth_v1_auth_proto_init() {
	if File_api_proto_tsundoku_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_tsundoku_auth_v1_auth_proto_rawDesc), len(file_api_proto_tsundoku_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_tsundoku_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_proto_tsundoku_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_api_proto_tsundoku_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_api_proto_tsundoku_auth_v1_auth_proto = out.File
	file_api_proto_tsundoku_auth_v1_auth_proto_goTypes = nil
	file_api_proto_tsundoku_auth_v1_auth_proto_depIdxs = nil
}
